### ISSUE TITLE
Icon color?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [adorade/boodark#9]
Hi

just installed the theme and really like it; one question though, the only thing I am not biggest fan (just a personal taste) of is the cyan icons. I'd like something more "muted" so to speak, like from the [Nord palette](https://www.nordtheme.com/). I played around with trying to override their colors int eh dev inspector but no luck. Is there some way for me to change them?

thanks!

**Comment by adorade** [comment]
Hi @YouveGotMeowxy. Glad you like the BooDark theme. I chose cyan for the icons because I wanted to make them stand out. If you want to change their color, you can do it in two ways (e.g. nord icon color: #88c0d0):
1. Edit the `css/theme.css` file: find and replace `fill="%230dcaf0"` with `fill="%2388c0d0"`.
2. Recompile the css files from scss, replace in `scss/_icons.scss`: `$svg-color: $pma-link-color;` with `$svg-color: #88c0d0;`.

![pma-nord-icons-color](https://user-images.githubusercontent.com/6474149/198567060-a5e805aa-1b32-409d-89f0-1cd01045f899.png)

Thanks for the suggestion with the Nord palette. Looks good. I'm waiting for feedback from you ;)

**Comment by YouveGotMeowxy** [comment]
Hi

Thanks for your help. I gave up, lol. the scss stuff is over my head right now and no time to go through the learning curve. I tried installing node, npm, sass, and Scout but then ran into issues with paths like `../../../node_modules/bootstrap/scss/_root.scss` not being found, so then I pointed to my Windows path where it was installed, and then started getting undefined variable errors in the imported files, and ... that was enough for me.

**Comment by adorade** [comment]
Hi @YouveGotMeowxy, don't give up, lol! You are on the right track, you just made a small mistake! Let me help you! You get the `../../../node_modules/bootstrap/scss/_root.scss` error because you haven't installed the project's dependencies correctly. So, let's resume the process, step by step:

1. Download the source-code of [boodark repo](https://github.com/adorade/boodark/archive/refs/heads/main.zip)
2. Extract the archive to wherever you want (eg D:\Projects)
3. Open `D:\Projects\boodark` in command-prompt (cmd)
4. Run `yarn install` ( or `npm install`) to install dependencies

Then open ScoutApp (see the screenshot below):

1. Add  `D:\Projects\boodark` to ScoutApp
2. Set **Input Folder:** to `D:/Projects/boodark/themes/boodark/scss`
3. Set **Output Folder:** to `D:/Projects/boodark/themes/boodark/css`
4. Run `boodark` project
5. Replace in `boodark/themes/boodark/scss/_icons.scss`: `$svg-color: $pma-link-color;` with `$svg-color: #88c0d0;`
6. Next, you find the new `theme.css` in `boodark/themes/boodark/css` 

![pma-nord-build](https://user-images.githubusercontent.com/6474149/198845228-9e71224d-8b9a-4fd3-8872-2ef16bb2c6be.png)

No scss learning curve! Just tips & tricks for today ;) Let me know if it works for you

**Comment by YouveGotMeowxy** [comment]
@adorade THANK YOU!

The Yarn is what I was missing. I've never used yarn before, so you taught me a new trick! :D

**Comment by adorade** [comment]
I'm glad I could help you. If everything is fine, you can close the issue. :wink:

**Comment by YouveGotMeowxy** [comment]
I really appreciate all of the help :)

Just so I know what's happening; if I make changes to the theme.css itself in the /css folder, do those changes get overwritten when Scout compiles the scss files? The compiling is where I get a lil bit thrown, lol. Like, I don't know whether to edit the files in the scss folder, or css folder, or both sometimes.

**Comment by adorade** [comment]
If you make changes in `theme.css`, they will be overwritten when Scout compiles the `scss` files into `css`. Compilation is one-way, **from scss to css**. See [BooDark build](https://github.com/adorade/boodark#building). In "development mode" sourcemaps are used, which tell you exactly which scss file to modify in case you want to customize (eg, using DevTools in Chrome).

To learn scss a good starting point: [Sass Basics](https://sass-lang.com/guide).
At the same time, you can find a lot of tutorials on the internet if you google it for "compile scss to css".

I will close this issue. If you find any error, please open a new issue. Happy learning! :wink:
